# Generated by Django 3.0.7 on 2021-02-16 13:46

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AporteCertificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte_certificacion', models.CharField(max_length=50, verbose_name='Aporte Certificación (Bs)')),
                ('aporte_certificacion_deno', models.CharField(default='CERTIFICADO', max_length=20, unique=True, verbose_name='Nombre del certificado')),
            ],
            options={
                'verbose_name': 'aporte_certificación',
                'verbose_name_plural': 'aportes_certificación',
            },
        ),
        migrations.CreateModel(
            name='AporteMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte_mensual_deno', models.CharField(default='AMU', max_length=3, unique=True, verbose_name='Denominación')),
                ('aporte_mensual', models.CharField(max_length=50, verbose_name='Aporte Mensual (Bs)')),
                ('fecha_inicio_cobros', models.DateField(default=datetime.datetime(2021, 2, 16, 13, 46, 47, 180731, tzinfo=utc), verbose_name='Fecha de inicio de cobros mensuales')),
            ],
            options={
                'verbose_name': 'aporte_mensual',
                'verbose_name_plural': 'aportes_mensuales',
            },
        ),
        migrations.CreateModel(
            name='RegistrarUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=4, verbose_name='Matrícula')),
                ('ci', models.CharField(max_length=50, verbose_name='CI')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('usuario_vivo', models.BooleanField(default=True, verbose_name='Está vivo')),
                ('password_new1', models.CharField(default='NuevaClave1', max_length=100, verbose_name='NewPassword1')),
                ('password_new2', models.CharField(default='NuevaClave2', max_length=100, verbose_name='NewPassword2')),
                ('password1', models.CharField(max_length=100, verbose_name='Password1')),
                ('password2', models.CharField(max_length=100, verbose_name='Password2')),
                ('fecha_registro', models.DateField(default=datetime.datetime(2021, 2, 16, 13, 46, 47, 180731, tzinfo=utc), verbose_name='Fecha de registro personalizada')),
            ],
            options={
                'verbose_name': 'CampoUsuario',
                'verbose_name_plural': 'CamposUsuarios',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricula', models.CharField(max_length=4, verbose_name='Matrícula')),
                ('foto', models.ImageField(blank=True, max_length=255, null=True, upload_to='fotos_usuarios/', verbose_name='Foto')),
                ('apell_pat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Paterno')),
                ('apell_mat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('ci', models.CharField(max_length=50, verbose_name='CI')),
                ('direcc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('fecha_registro', models.DateField(default=datetime.datetime(2021, 2, 16, 13, 46, 47, 165614, tzinfo=utc), verbose_name='Fecha de registro personalizada')),
                ('usuario_vivo', models.BooleanField(default=True, verbose_name='Vivo')),
                ('estado_usuario', models.BooleanField(default=True, verbose_name='Activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AporteAfiliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte_dona_afil', models.CharField(default=0, max_length=50, verbose_name='Aporte por donación')),
                ('fecha_pago', models.DateField(default=datetime.datetime(2021, 2, 16, 13, 46, 47, 185790, tzinfo=utc), verbose_name='Fecha de pago')),
                ('comprobante', models.CharField(default=0, max_length=6, unique=True, verbose_name='Comprobante de transacción')),
                ('afiliado', models.ForeignKey(limit_choices_to={'groups__name': 'Afiliado'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aporte_certif_afil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProyectoApp.AporteCertificacion')),
                ('aporte_mensual_afil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProyectoApp.AporteMensual')),
                ('recaudador', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Recaudador'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aporte_recaudador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aporte_afiliado',
                'verbose_name_plural': 'aportes_afiliado',
            },
        ),
    ]
