# Generated by Django 3.0.7 on 2021-03-23 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0004_auto_20210217_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='aporteafiliado',
            name='talonario',
            field=models.CharField(default=0, max_length=8, verbose_name='Talonario de cobro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='asist_event_inter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asistencia a eventos internacionales'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='beneficiarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Beneficiarios'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargo_actual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo actual'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargos_admin_pub',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargos desemp. en la Administración Pública'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargos_judic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargos desemp. en el ramo judicial'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargos_priv_otras',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargos desemp. en empresas privadas u otras instituciones'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='direc_ofic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección oficina'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ejer_cated',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ejercicio en la Cátedra'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ent_pub',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Entidad pública- Abogado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='espec_ejer_der',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad en el ejercicio del Derecho'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='est_civil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estud_espec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estudios de especialización'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_ol',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha en que se otorgó la Licenciatura'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_tg',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tesis o Grado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_tit_pn',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha título Provición Nacional'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='inst_aseg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instituciones donde se haya asegurado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lugar_nac',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_ruc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de RUC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='observ',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prod_jur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Producciones jurídicas'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recon_obt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reconocimientos obtenidos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel_ofic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de oficina'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiempo_ejec_prof_sd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo de ejecución profesional sin dependencia (BUFETE)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='univ_estud',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Universidad de estudio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='univ_lic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Universidad que le otorgó la Licenciatura'),
        ),
        migrations.AlterField(
            model_name='aporteafiliado',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 14, 20, 34, 492411, tzinfo=utc), verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='fecha_inicio_cobros',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 14, 20, 34, 487900, tzinfo=utc), verbose_name='Fecha de inicio de cobros mensuales'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 14, 20, 34, 477837, tzinfo=utc), verbose_name='Fecha de matrícula ICAP'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 14, 20, 34, 482846, tzinfo=utc), verbose_name='Fecha de registro personalizada'),
        ),
    ]
