# Generated by Django 3.0.7 on 2021-03-26 02:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0006_auto_20210325_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporteafiliado',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 2, 39, 49, 350429, tzinfo=utc), verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='fecha_inicio_cobros',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 2, 39, 49, 350429, tzinfo=utc), verbose_name='Fecha de inicio de cobros mensuales'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 2, 39, 49, 340305, tzinfo=utc), verbose_name='Fecha de matrícula ICAP'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 2, 39, 49, 350429, tzinfo=utc), verbose_name='Fecha de registro personalizada'),
        ),
    ]
