# Generated by Django 3.0.7 on 2021-03-28 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0008_auto_20210326_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarusuario',
            name='apell_mat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido (M)'),
        ),
        migrations.AddField(
            model_name='registrarusuario',
            name='apell_pat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido (P)'),
        ),
        migrations.AddField(
            model_name='registrarusuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='aporteafiliado',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 15, 35, 20, 507967, tzinfo=utc), verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='fecha_inicio_cobros',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 15, 35, 20, 507967, tzinfo=utc), verbose_name='Fecha de inicio de cobros mensuales'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 15, 35, 20, 507967, tzinfo=utc), verbose_name='Fecha de matrícula ICAP'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 15, 35, 20, 507967, tzinfo=utc), verbose_name='Fecha de registro personalizada'),
        ),
    ]
