# Generated by Django 3.0.7 on 2021-03-28 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0009_auto_20210328_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporteafiliado',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 15, 43, 52, 110736, tzinfo=utc), verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='fecha_inicio_cobros',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 15, 43, 52, 110736, tzinfo=utc), verbose_name='Fecha de inicio de cobros mensuales'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 15, 43, 52, 100977, tzinfo=utc), verbose_name='Fecha de matrícula ICAP'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='apell_mat',
            field=models.CharField(default='hola', max_length=50, verbose_name='Apellido (M)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='apell_pat',
            field=models.CharField(default='hola', max_length=50, verbose_name='Apellido (P)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 15, 43, 52, 100977, tzinfo=utc), verbose_name='Fecha de registro personalizada'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='first_name',
            field=models.CharField(default='hola', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
