# Generated by Django 3.0.7 on 2021-03-30 02:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0010_auto_20210328_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporteafiliado',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 2, 26, 4, 629098, tzinfo=utc), verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='aporteafiliado',
            name='talonario',
            field=models.CharField(max_length=8, unique=True, verbose_name='Talonario de cobro'),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='fecha_inicio_cobros',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 2, 26, 4, 629098, tzinfo=utc), verbose_name='Fecha de inicio de cobros mensuales'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 2, 26, 4, 613473, tzinfo=utc), verbose_name='Fecha de matrícula ICAP'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 2, 26, 4, 629098, tzinfo=utc), verbose_name='Fecha de registro personalizada'),
        ),
    ]
