# Generated by Django 3.0.7 on 2021-03-30 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0011_auto_20210329_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarusuario',
            name='estado_usuario',
            field=models.BooleanField(default=True, verbose_name='Está ACTIVO'),
        ),
        migrations.AlterField(
            model_name='aporteafiliado',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 14, 6, 26, 373767, tzinfo=utc), verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='fecha_inicio_cobros',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 14, 6, 26, 365770, tzinfo=utc), verbose_name='Fecha de inicio de cobros mensuales'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 14, 6, 26, 357776, tzinfo=utc), verbose_name='Fecha de matrícula ICAP'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 14, 6, 26, 365770, tzinfo=utc), verbose_name='Fecha de registro personalizada'),
        ),
    ]
