# Generated by Django 3.0.7 on 2021-03-30 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0012_auto_20210330_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporteafiliado',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 15, 26, 59, 190862, tzinfo=utc), verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='aporteafiliado',
            name='talonario',
            field=models.CharField(max_length=8, verbose_name='Talonario de cobro'),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='fecha_inicio_cobros',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 15, 26, 59, 190862, tzinfo=utc), verbose_name='Fecha de inicio de cobros mensuales'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 15, 26, 59, 190862, tzinfo=utc), verbose_name='Fecha de matrícula ICAP'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 15, 26, 59, 190862, tzinfo=utc), verbose_name='Fecha de registro personalizada'),
        ),
    ]
