# Generated by Django 3.0.7 on 2021-04-03 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0025_auto_20210402_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporteafiliado',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2021, 4, 3, 11, 15, 57, 249719, tzinfo=utc), verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='fecha_inicio_cobros',
            field=models.DateField(default=datetime.datetime(2021, 4, 3, 11, 15, 57, 249719, tzinfo=utc), verbose_name='Fecha de inicio de cobros mensuales'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 4, 3, 11, 15, 57, 241689, tzinfo=utc), verbose_name='Fecha de matrícula ICAP'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 4, 3, 11, 15, 57, 249719, tzinfo=utc), verbose_name='Fecha de registro personalizada'),
        ),
    ]
