# Generated by Django 3.0.7 on 2021-04-09 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0028_auto_20210408_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporteafiliado',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 2, 14, 45, 264352, tzinfo=utc), verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='fecha_inicio_cobros',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 2, 14, 45, 264352, tzinfo=utc), verbose_name='Fecha de inicio de cobros mensuales'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 2, 14, 45, 264352, tzinfo=utc), verbose_name='Fecha de matrícula ICAP'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 2, 14, 45, 264352, tzinfo=utc), verbose_name='Fecha de registro personalizada'),
        ),
    ]
